### ISSUE TITLE
Use a project structure and/or a frontend framework 

### ISSUE THREAD

**Issue by GuillaumeCz** [hyundotio/magicpad#10]
Currently, all the source code is placed in one huge file (app/js/main.js) which complicates the comprehension, maintenance and evolution of the project.

Owing to the fact that this is a pure front end project, it could be interesting to use a framework or frontend library in order to provide a basic structure (Angular/React/Vue/whatever... ;) )

**Comment by hyundotio** [comment]
Thank you! This is definitely my next step. I want to consolidate, remove redundant functions, and part out the main.js file then try to learn a framework (probably React) then move the project there.

**Comment by GuillaumeCz** [comment]
I was also thinking about a React(-Redux) structure ! 
It may be interesting to start from a boilerplate (react only --> https://github.com/facebook/create-react-app or react+redux --> https://github.com/notrab/create-react-app-redux, there is so much other projects / possibilities... !)

;)

**Comment by hyundotio** [comment]
Hello, I componentized the HTML and JS much as I can. I think this at this point, I will try to learn React best as possible and rewrite the components slowly in a different git :)

**Comment by GuillaumeCz** [comment]
Haha perfect ! That's was fast ! 
I've worked a few time with React, let me know when you're rewriting the app, I'll be glad to eventually help you (If I correctly manage my spare time) ! 

You're doing a great job :D
