### ISSUE TITLE
Upload keys to public server

### ISSUE THREAD

**Issue by Deadlyelder** [hyundotio/magicpad#7]
Nice tool! Can see a lot of potential from this :)

Would suggest having an option for uploading the public key to one of the key servers. Since the tool is intended for beginners, allowing this option to directly upload the key would be nice addition.

Regards

**Comment by hyundotio** [comment]
I’ll see if I can work on a flow for this! :)

**Comment by hyundotio** [comment]
Please try pulling / downloading the new executables. Upload key + searching key is now added!

**Comment by Deadlyelder** [comment]
Nice! That was super fast :)

**Comment by hyundotio** [comment]
It had some bugs but now it's all fixed :) I also added a mobile UI too when it's running on the web-browser. Maybe I'll tackle it soon  :) Thanks!
